# Generated by Django 3.2.13 on 2022-05-25 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacherApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnb', models.CharField(max_length=255, verbose_name='课程号')),
                ('cname', models.CharField(max_length=255, verbose_name='课程名')),
                ('cpicture', models.CharField(max_length=255, verbose_name='课程照片')),
                ('create_time', models.DateTimeField(verbose_name='申请通过时间')),
                ('ckind', models.CharField(max_length=255, verbose_name='课程种类')),
                ('credit', models.IntegerField(verbose_name='学分')),
                ('open_time', models.DateTimeField(verbose_name='开课时间')),
                ('cinfo', models.CharField(max_length=1000, verbose_name='课程简介')),
                ('apply', models.IntegerField(choices=[(0, '未通过'), (1, '通过')], verbose_name='是否申请通过')),
                ('teacher', models.ForeignKey(db_column='Teacher.Ttunmb', on_delete=django.db.models.deletion.CASCADE, to='teacherApp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('Stunmb', models.CharField(max_length=255, verbose_name='学号')),
                ('phonenb', models.CharField(max_length=11, verbose_name='手机号')),
                ('Sname', models.CharField(max_length=255, verbose_name='学生姓名')),
                ('School', models.CharField(max_length=255, verbose_name='学校')),
            ],
        ),
        migrations.CreateModel(
            name='course_selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_time', models.DateTimeField(verbose_name='选课时间')),
                ('grade', models.IntegerField(verbose_name='成绩')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.student')),
            ],
        ),
    ]
