# Generated by Django 3.2.13 on 2022-05-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('Ttunmb', models.CharField(max_length=255, verbose_name='教师号')),
                ('phonenb', models.CharField(max_length=11, verbose_name='手机号')),
                ('Tname', models.CharField(max_length=255, verbose_name='教师姓名')),
                ('School', models.CharField(max_length=255, verbose_name='学校')),
            ],
        ),
    ]
